# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# EMBEDDED SERVER CONFIGURATION

server:
    port: 8080
    
spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Grunt + BrowserSync for livereload
    datasource:
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/dbrdvmedecins3?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: admin
        password: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    #data:
        #elasticsearch:
            #cluster-name:
            #cluster-nodes:
            #properties:
                #path:
                  #logs: target/elasticsearch/log
                  #data: target/elasticsearch/data
    #mail:
        #host: localhost
    #messages:
        #cache-seconds: 1
    thymeleaf:
        cache: false
        enabled: true 
        mode: HTML5
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        check-template-location: true
        content-type: text/html
        template-resolver-order: 0

# LIQUIBASE

liquibase:
    enabled: false # enable liquibase support
    contexts: dev # runtime contexts to use.
    change-log:  classpath:config/liquibase/master.xml # classpath:/db/changelog/db.changelog-master.yaml # Change log configuration path.
    check-change-log-location: true # Check the change log location exists.
    default-schema: dbrdvmedecins3 # Default database schema.
    drop-first: false # Drop the database schema first.    
    #labels:  # Comma-separated list of runtime labels to use.
    #parameters.*:  # Change log parameters.
    #--database access no need to set, the primary configured data source is used
    #password:  # Login password of the database to migrate.
    #url:  # JDBC url of the database to migrate.
    #user:  # Login user of the database to migrate.

    
# ENDPOINTS
#endpoints:
#    enabled: true
#    autoconfig.enabled: true
#    beans.enabled: false
#    configprops.enabled: false
#    dump.enabled: false
#    env.enabled: false
#    health.enabled: true
#    info.enabled: true
#    metrics.enabled: false
#    mappings.enabled: false
#    shutdown.enabled: false
#    trace.enabled: false

# ===================================================================
# ZocDoc specific properties
# ===================================================================

zocdoc:
    datasource: # JHipster-specific configuration, in addition to the standard spring.datasource properties
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 3e374cdf5c1b0dcb78602e6cf080979a2774e468        
    #mail: # specific JHipster mail property, for standard properties see MailProperties
        #from: jhipsterbank@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: zocdoc
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512    
