# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    
spring:
    application:
        name: zocdoc
    jpa:
        open-in-view: false # Register OpenEntityManagerInViewInterceptor. Binds a JPA EntityManager to the thread for the entire processing of the request.
        generate-ddl: false # (false)Initialize the schema on startup, not used if Hibernate autoconfig is active. see (http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html)            
        hibernate:
            ddl-auto: update # (none) DDL mode (none, validate, update, create, create-drop), shortcut for the "hibernate.hbm2ddl.auto" property.
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy # change the name from camel to _ format
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# ZocDoc specific properties
# ===================================================================

zocdoc:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    #mail:
        #from: jhipsterbank@localhost
    #swagger:
        #title: jhipsterbank API
        #description: jhipsterbank API documentation
        #version: 0.0.1
        #termsOfServiceUrl:
        #contact:
        #license:
        #licenseUrl:
